project:
  type: website
  output-dir: docs
  resources:
    - clouds

website:
  title: "Home"
  navbar:
    left:
      - href: https://danexistsmaybe.github.io/poetry.html
        text: Poetry
      - href: mini1.qmd
        text: Mini Project 1
      - href: mini2.qmd
        text: Mini Project 2
      - href: mini4.qmd
        text: Mini Project 4

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full
    includes:
      after-body: crumpet.html