project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - href: https://danexistsmaybe.github.io/
        text: Main Site
      - href: https://danexistsmaybe.github.io/poetry.html
        text: Poetry
      - href: https://danexistsmaybe.github.io/R/docs
        text: R Portfolio
      - href: https://danexistsmaybe.github.io/R/docs
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full